### PR TITLE
fix CI build

### PR DESCRIPTION
**Pull request by justindujardin**
- downgrade to pydocstyle < 4.0
 - fix lint errors
 - move tests to sibling in root to avoid linting tests
 - make traceback error handling compatible with TF 2.0 logging

### CODE REVIEW

**Comment by Guillemdb** [comment]
I am getting the same `coverage combine failed` error in `fragile`. Do you know why this is happening?

**Comment by justindujardin** [comment]
I think it's unhappy with the python command you're using to invoke the tests. The `unittest` package can probably be used, but I usually invoke `pytest` directly. 

Changing to pytest in the coverage command worked locally, but for some reason Travis executed against the wrong commit when I pushed the last changes. 

I'll try once more with a better TF 1.x+2.x logging fix, and hopefully the build will get the right commit this time. 👍

**Comment by Guillemdb** [comment]
Wow thanks! I really appreciate it. Making this fixes is something I had pending since a long time ago :D

**Comment by justindujardin** [comment]
It seems there's one more problem, you test against python 3.5, but the codebase uses f-strings which were only introduced in 3.6. 

Do you prefer removing the f-strings or dropping python < 3.6 from the test grid?

**Comment by justindujardin** [comment]
I guessed and replaced python 3.5 with python 3.8. If you prefer to have 3.5 support back let me know, otherwise I think this is done.

**Comment by Guillemdb** [comment]
Thanks! I was just gonna ask you to remove support of python 3.5. Thanks a lot!

I am gonna be merging this, and take care of the tests coverage myself next week.

**Pull request merged**
